added crud for locations
acselp/varatic_prim_teza pull request #9
Opened 2023-04-19 13:45 UTC by acselp

2023-04-19 14:04 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/LocationController.cs
> +    [AllowAnonymous]
why anonymous

2023-04-19 14:04 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/CounterModels/LocationCreateModel.cs
> +public class LocationCreateModel
rename to
```suggestion
public class CounterCreateModel
```

2023-04-19 14:04 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/CounterModels/LocationCreateModel.cs
same here also rename

2023-04-19 14:04 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Startup.cs
> +        services.AddScoped<ILocationRepository, LocationRepository>();
register and CounterRepository

2023-04-19 14:04 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/AutoMapperProfiles/LocationProfile.cs
> +    }
why did you add user mappers in same file with location mappers, separate them

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            _logger.LogInformation("Creating location...");
without `...`

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            _logger.LogInformation("Creating location...");
Add validation

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            var validLocationModel = _mapper.Map<LocationModel>(locationEntity);
```suggestion
            var locationModel = _mapper.Map<LocationModel>(locationEntity);
```
why valid?

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            var userEntity = await _userRepository.GetById(locationEntity.UserId);
what if user not fount? validate if user exists before inserting in database

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            var userEntity = await _userRepository.GetById(locationEntity.UserId);
and you dont need to get user by id, you should use the user from location entity created

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                _logger.LogWarning("Location with id = " + id + " not found");
```suggestion
                _logger.LogWarning("Location with id {Id} not found", id);
```

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                throw new LocationNotFoundException("Location with id = " + id + " not found");
same here

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            return locationModel;
don't return anything

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                throw new LocationNotFoundException("Location with id = " + id + " not found");
check comments before

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +
empty line

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/LocationController.cs
> +    [AllowAnonymous]
why anonymous

2023-04-21 08:12 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                throw new LocationNotFoundException("Location with id = " + id + " not found");
check comments before

2023-04-22 12:11 UTC, ion-topala requested changes

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Configurator.cs
> +        serviceCollection.AddValidatorsFromAssemblyContaining<CounterUpdateModelValidator>();
create a `Configurator` class in `Validation` folder and register these validators there

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +                _logger.LogWarning("Counter with barcode = " + counter.BarCode + " already exists.");
when you write logs you always should use string interpolation, barcode should be generated on backend, and there won't be any cases when barcode are identical, so this verification is redundant and delete barcode from update and create model.
Also a I don't see where barcode is generated.

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Domain/Entity/CounterEntity.cs
> +    public string BarCode { get; set; }
rename to `Barcode`

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +            await _counterCreateValidator.ValidateAndThrowAsync(counter);
call validator before mapper

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +            var location = await _locationRepository.GetById(counter.LocationId);
you can use location entity from counter entity

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/CounterModels/CounterUpdateModel.cs
> +    public string BarCode { get; set; }
barcode mustn't be updated from frontend

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/CounterModels/CounterUpdateModel.cs
> +    public string BarCode { get; set; }
also rename to `Barcode`

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/LocationModels/LocationUpdateModel.cs
> +    public int Id { get; set; }
why did you add `Id` in update model

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Validation/CounterCreateModelValidator.cs
> +    }
there is no logic in this validator

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Validation/CounterUpdateModelValidator.cs
> +    }
also here

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Validation/LocationCreateModelValidator.cs
> +    }
add logic

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Validation/UserUpdateModelValidator.cs
> +    }
please add logic

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/CounterController.cs
> +            return BadRequest("counter_not_found", "Counter not found");
create a `ApiErrorCodes` class where will be stored all this errors and same for the messages

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/CounterController.cs
> +        }
also you need to catch ValidationException

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/LocationController.cs
> +    [AllowAnonymous]
please don't just mark conversation as resolved and forget about it

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim/Controllers/LocationController.cs
> +        }
catch ValidationException

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +    private ILocationRepository _locationRepository;
also readonly

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +
empty line

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +
empty line

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            var userEntity = await _userRepository.GetById(locationEntity.UserId);
resolve conversation

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                throw new LocationNotFoundException("Location with id = " + id + " not found");
use interpolation

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +            return locationModel;
resolve conversation

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/LocationManager.cs
> +                throw new LocationNotFoundException("Location with id = " + id + " not found");
use interpolation

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/UserManager.cs
> +            await _userUpdateValidator.ValidateAndThrowAsync(userUpdateModel);
validate before query db

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/UserManager.cs
> +            if (await _userRepository.EmailExists(userUpdateModel.Email))
for now let's remove email from `UserUpdateModel`

2023-04-22 12:11 UTC, ion-topala commented on Back-End/VaraticPrim/VaraticPrim.Framework/Models/CounterModels/CounterCreateModel.cs
> +    public string BarCode { get; set; }
```suggestion
    public string Barcode { get; set; }
```

2023-04-25 09:03 UTC, acselp commented on Back-End/VaraticPrim/VaraticPrim.Framework/Managers/CounterManager.cs
> +                _logger.LogWarning("Counter with barcode = " + counter.BarCode + " already exists.");
Bar code is the unique number on the water counter. And I thought this would be a good idea to use it as an ideantyfier.

2023-04-25 09:18 UTC, merged